### ISSUE TITLE
Compilation issue with x86_64->PPC cross compiler

### ISSUE THREAD

**Issue by Jazzzny** [iains/gcc-13-branch#22]
Hey there,

I've been trying to get a PPC cross compiler built on 64-bit Intel Snow Leopard 10.6.8, but I'm having trouble with the build.

After compiling and installing the prerequisites into /opt/gcc and cloning the repo, I'm configuring with
`../gcc-13-branch/configure --disable-multilib --with-gmp=/opt/gcc --with-mpfr=/opt/gcc --with-mpc=/opt/gcc --disable-nls --enable-languages=c --with-sysroot=/Developer/SDKs/MacOSX10.6.sdk --prefix=/opt/gcc --target=powerpc-apple-darwin10.8.0 --disable-bootstrap AR=/opt/gcc/bin/ar AS=/opt/gcc/bin/as LD=/opt/gcc/bin/ld AS_FOR_TARGET=/opt/gcc/bin/as AR_FOR_TARGET=/opt/gcc/bin/ar LD_FOR_TARGET=/opt/gcc/bin/ld RANLIB_FOR_TARGET=/opt/gcc/bin/ranlib RANLIB=/opt/gcc/bin/ranlib`

(The cctools and ld are compiled from the xtools package)

This builds up to libgcc, where it tries to use xgcc and fails with 
```
configure:3576: /Users/jazzzny/Desktop/gcctest/./gcc/xgcc -B/Users/jazzzny/Desktop/gcctest/./gcc/ -B/opt/gcc/powerpc-apple-darwin10.8.0/bin/ -B/opt/gcc/powerpc-apple-darwin10.8.0/lib/ -isystem /opt/gcc/powerpc-apple-darwin10.8.0/include -isystem /opt/gcc/powerpc-apple-darwin10.8.0/sys-include    -o conftest -g -O2   conftest.c  >&5
/var/folders/BP/BPBCcyw8Gke-CZni3KX7JE+++TI/-Tmp-//ccpGUOad.s:1:Unknown pseudo-op: .macosx_version_min
/var/folders/BP/BPBCcyw8Gke-CZni3KX7JE+++TI/-Tmp-//ccpGUOad.s:1:Rest of line ignored. 1st junk character valued 49 (1).
configure:3579: $? = 1
configure:3792: checking for suffix of object files
configure:3814: /Users/jazzzny/Desktop/gcctest/./gcc/xgcc -B/Users/jazzzny/Desktop/gcctest/./gcc/ -B/opt/gcc/powerpc-apple-darwin10.8.0/bin/ -B/opt/gcc/powerpc-apple-darwin10.8.0/lib/ -isystem /opt/gcc/powerpc-apple-darwin10.8.0/include -isystem /opt/gcc/powerpc-apple-darwin10.8.0/sys-include    -c -g -O2  conftest.c >&5
/var/folders/BP/BPBCcyw8Gke-CZni3KX7JE+++TI/-Tmp-//cc3IC9EC.s:1:Unknown pseudo-op: .macosx_version_min
/var/folders/BP/BPBCcyw8Gke-CZni3KX7JE+++TI/-Tmp-//cc3IC9EC.s:1:Rest of line ignored. 1st junk character valued 49 (1).
configure:3818: $? = 1
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "GNU C Runtime Library"
| #define PACKAGE_TARNAME "libgcc"
| #define PACKAGE_VERSION "1.0"
| #define PACKAGE_STRING "GNU C Runtime Library 1.0"
| #define PACKAGE_BUGREPORT ""
| #define PACKAGE_URL "http://www.gnu.org/software/libgcc/"
| /* end confdefs.h.  */
| 
| int
| main ()
| {
| 
|   ;
|   return 0;
| }
configure:3832: error: in `/Users/jazzzny/Desktop/gcctest/powerpc-apple-darwin10.8.0/libgcc':
configure:3834: error: cannot compute suffix of object files: cannot compile
See `config.log' for more details
```

Even just trying to compile a "Hello world" program with the xgcc, it fails with
`Unknown pseudo-op: .macosx_version_min` and `Rest of line ignored. 1st junk character valued 49 (1).`.

Any advice on how to proceed?

Thanks,

**Comment by iains** [comment]
The configure has determined that the assembler you used to build the compiler supports `.macosx_version_min`  but the target tools do not?

perhaps adding to the configure   `--with-as=/opt/gcc/bin/as --with-ld=/opt/gcc/bin/ld`

what toolchain are you using to build this?

**Comment by Jazzzny** [comment]
I'm currently building with GCC 11 from MacPorts. I'll try building an x86_64-native GCC 13 first and then using it as a bootstrap.

**Comment by Jazzzny** [comment]
Okay, well, bit of an update:

I got the GCC 13 cross compiler compiled, I had to do it on a different 10.6 install which doesn't have MacPorts installed at all (Bootstrapped using GCC 4.2 -> GCC 10). It seems to work perfectly when testing.

Thanks for the pointers (and for ensuring that these funky, old configurations still work in modern GCC)!
