### ISSUE TITLE
[powerpc-darwin] ICE: in decode_addr_const, at varasm.c:3059

### ISSUE THREAD

**Issue by barracuda156** [iains/gcc-13-branch#3]
@iains Could this be addressed in the next release (or next-next, I do not know the schedule)? https://gcc.gnu.org/bugzilla/show_bug.cgi?id=105522
If you get a chance to deal with it.

**Comment by iains** [comment]
this is an upstream issue not related to the branches here and is tracked in the BZ you mention.  To answer the schedule question, I do not know when I will have time to address it..

**Comment by barracuda156** [comment]
@iains Got it, thank you.
