### ISSUE TITLE
Build error with gcc 13.2 on Apple Silicon (Ventura 13.5)

### ISSUE THREAD

**Issue by mjsteinbaugh** [iains/gcc-13-branch#7]
Hi @iains and @fxcoudert ,

I'm now seeing this build error for gcc 13.2 on my M1 Mac:

```
config.status: creating config.h
config.status: executing default commands
gmake[2]: Leaving directory '/private/var/folders/9b/4gh0pghx1b71jjd0wjh5mj880000gn/T/koopa.rSqv2ZIBzWk8/build'
gmake[1]: *** [Makefile:24321: stage1-bubble] Error 2
gmake[1]: Leaving directory '/private/var/folders/9b/4gh0pghx1b71jjd0wjh5mj880000gn/T/koopa.rSqv2ZIBzWk8/build'
gmake: *** [Makefile:1077: all] Error 2
```

My build script is here for reference:
https://github.com/acidgenomics/koopa/blob/develop/lang/bash/include/install/common/shared/gcc.sh

GCC 13.1 builds successfully for me on the same machine. Happy to help debug and try to sort this out.

Best,
Mike

**Comment by mjsteinbaugh** [comment]
Ah dang it, now I'm seeing a similar build issue with 13.1 that used to build successfully. I'll see if I can sort this out. I'm using Xcode CLT 14.3.1.0.1.1683849156

**Comment by iains** [comment]
> Hi @iains and @fxcoudert ,
> 
> I'm now seeing this build error for gcc 13.2 on my M1 Mac:
> 
> ```
> config.status: creating config.h
> config.status: executing default commands
> gmake[2]: Leaving directory '/private/var/folders/9b/4gh0pghx1b71jjd0wjh5mj880000gn/T/koopa.rSqv2ZIBzWk8/build'
> gmake[1]: *** [Makefile:24321: stage1-bubble] Error 2
> gmake[1]: Leaving directory '/private/var/folders/9b/4gh0pghx1b71jjd0wjh5mj880000gn/T/koopa.rSqv2ZIBzWk8/build'
> gmake: *** [Makefile:1077: all] Error 2
> ```

This is not enough information to help - actually, that is not showing the error itself (which is most likely a missing file).

BTW on macOS 12 the sources [from here] for both 13.1 and 13.2 build for me using Xcode CLT 14.3.

**Comment by mjsteinbaugh** [comment]
Thanks @iains , I figured it out -- I'm trying to update a build script for [sambamba](https://github.com/biod/sambamba), which requires gcc and ldc. It also requires that requires `LIBRARY_PATH` to be set. Having this variable defined breaks the gcc install at that point.

**Comment by iains** [comment]
FWIW, we are getting close to being able to build D natively on Arm64.

**Comment by mjsteinbaugh** [comment]
@ians Awesome I'm currently installing the D compilers using the shell script at https://dlang.org/download.html but would prefer to build them from source.
